"""
--- L9_META ---
l9_schema: 2
origin: l9-template
engine: graph
layer: [meta]
tags: [governance, portability]
status: active
--- /L9_META ---

Render `l9-meta.yaml`.

Hand-rendered rather than `yaml.safe_dump`ed: this file is meant to be read and
edited by humans, so section comments and flow-style lists matter more than
round-trip purity.
"""

from __future__ import annotations

from typing import Any

from tools.l9_meta.config import SETTABLE

_HEADER = """\
# L9_META source of truth for this repository.
#
# Resolution, most specific last:
#   defaults  ->  rules (last match wins)  ->  overrides[exact path]
#
# Generated by `python -m tools.l9_meta.cli sync --adopt` from headers already
# present on disk. Edit freely; re-running sync will not clobber hand edits
# unless you pass --adopt again.
"""


def _flow(items: list[str] | tuple[str, ...]) -> str:
    return "[" + ", ".join(str(i) for i in items) + "]"


def _scalar(value: Any) -> str:
    if isinstance(value, (list, tuple)):
        return _flow(value)
    return str(value)


def _fields(values: dict[str, Any], indent: str) -> list[str]:
    out = []
    for key in SETTABLE:
        if key in values:
            out.append(f"{indent}{key}: {_scalar(values[key])}")
    return out


def render(
    engine: str,
    defaults: dict[str, Any],
    rules: list[dict[str, Any]],
    overrides: dict[str, dict[str, Any]],
    exclude: list[str],
    vocabulary: dict[str, Any] | None = None,
) -> str:
    lines = [_HEADER, f"engine: {engine}", ""]

    lines.append("defaults:")
    lines.extend(_fields(defaults, "  "))
    lines.append("")

    lines.append("exclude:")
    for pattern in exclude:
        lines.append(f"  - {pattern}")
    lines.append("")

    if vocabulary:
        lines.append("vocabulary:")
        for key in ("origin", "status", "layer"):
            if vocabulary.get(key):
                lines.append(f"  {key}: {_flow(vocabulary[key])}")
        tags = vocabulary.get("tags") or {}
        if tags:
            lines.append("  tags:")
            lines.append(f"    max_tags: {tags.get('max_tags', 3)}")
            for facet in ("family", "capability", "concern"):
                if tags.get(facet):
                    lines.append(f"    {facet}:")
                    for value in tags[facet]:
                        lines.append(f"      - {value}")
        lines.append("")

    lines.append("# Directory rules. A trailing `/` means everything beneath.")
    lines.append("rules:")
    for rule in rules:
        lines.append(f"  - path: {_quote(rule['path'])}")
        lines.extend(_fields(rule, "    "))
    lines.append("")

    lines.append("# Per-file values for paths whose directory says nothing useful.")
    lines.append("overrides:")
    for path in sorted(overrides):
        lines.append(f"  {_quote(path)}:")
        lines.extend(_fields(overrides[path], "    "))
    lines.append("")

    return "\n".join(lines)


def _quote(path: str) -> str:
    """Quote a path key. Spaces, `#`, and leading `.` all need it in YAML."""
    return '"' + path.replace('"', '\\"') + '"'
